# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 10:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuteurLivre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Auteur')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(blank=True, null=True)),
                ('date_retour', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lecteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('langue', models.CharField(choices=[('FR', 'Français'), ('ENG', 'Anglais')], default='FR', max_length=5)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_location', models.DateField()),
                ('date_fin_location', models.DateField(blank=True, null=True)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('lecteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Lecteur')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Livre')),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Livre')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Personne')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Livre'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Personne'),
        ),
        migrations.AddField(
            model_name='lecteur',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Livre'),
        ),
        migrations.AddField(
            model_name='lecteur',
            name='personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Personne'),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Personne'),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Proprietaire'),
        ),
        migrations.AddField(
            model_name='auteurlivre',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Livre'),
        ),
    ]
