# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160304_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
