# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160304_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='localite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personne',
            name='prenom',
            field=models.CharField(max_length=50),
        ),
    ]
